version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./src:/src:cached
      #- node_modules:/src/node_modules
      # ↑ 次回起動後にコメントアウトを解除
    working_dir: "/src"
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
  nginx:
    build:
      dockerfile: "./docker/nginx/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"
  php-fpm:
    build:
      dockerfile: "./docker/php-fpm/Dockerfile"
    volumes:
      - "./src:/var/www/html"
volumes:
  node_modules:
